# Generated by Django 2.1.5 on 2022-09-13 18:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=30)),
                ('imagen', models.ImageField(null=True, upload_to='categoria/')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_propiedad', models.CharField(choices=[('venta', 'venta'), ('arriendo', 'arriendo')], max_length=10)),
                ('precio', models.PositiveIntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('numero_camas', models.PositiveIntegerField()),
                ('numero_banos', models.PositiveIntegerField()),
                ('numero_estacionamiento', models.PositiveIntegerField()),
                ('servicios', models.CharField(blank=True, choices=[('', '---------'), ('PISCINA', 'piscina'), ('GIMNASIO', 'gimnasio'), ('SPA', 'spa'), ('JACUZZI', 'jacuzzi'), ('INTERNET', 'internet'), ('CABLE', 'cable'), ('SECURITY', 'security'), ('LAVANDERIA', 'lavanderia'), ('PARKING', 'parking'), ('BODEGA', 'bodega'), ('OFICINA', 'oficina'), ('RESTAURANTE', 'restaurante'), ('CENTRO DE EVENTOS', 'centro de eventos')], default=None, max_length=100, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='propiedad/')),
                ('imagen1', models.ImageField(null=True, upload_to='propiedad/')),
                ('imagen2', models.ImageField(null=True, upload_to='propiedad/')),
                ('imagen3', models.ImageField(null=True, upload_to='propiedad/')),
                ('imagen4', models.ImageField(null=True, upload_to='propiedad/')),
                ('imagen5', models.ImageField(null=True, upload_to='propiedad/')),
                ('locacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='propiedad.Categoria')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('notas', models.TextField()),
            ],
        ),
    ]
