# Generated by Django 2.1.5 on 2022-09-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0003_auto_20220915_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='modalidad',
            field=models.CharField(choices=[('', '---------'), ('ARRIENDO', 'Arriendo'), ('Venta', 'Venta')], default=None, max_length=100),
        ),
    ]
