# Generated by Django 2.1.5 on 2022-09-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acerca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.TextField()),
                ('mision', models.TextField()),
                ('imagen', models.ImageField(upload_to='acerca/')),
            ],
        ),
    ]
